# Generated by Django 3.1.4 on 2020-12-29 15:16

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import game_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckGameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.TimeField(auto_now_add=True)),
                ('send_to', models.CharField(max_length=30)),
                ('recieved_from', models.CharField(max_length=30)),
                ('is_replied', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Requests',
                'verbose_name_plural': 'Requests',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('cards', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), size=None), default=list, size=None)),
                ('hasPlayed', models.BooleanField(default=False)),
                ('hasPicked', models.BooleanField(default=False)),
                ('div', models.CharField(max_length=30, null=True)),
                ('game_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_app.checkgamesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='playboard', max_length=30)),
                ('card_dict', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('div', models.CharField(default='#board', max_length=30)),
                ('game_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_app.checkgamesession')),
            ],
        ),
        migrations.CreateModel(
            name='DealBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='dealboard', max_length=30)),
                ('cards', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), size=None), default=game_app.models.get_deck, size=None)),
                ('div', models.CharField(default='dealboard-deck', max_length=30)),
                ('game_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_app.checkgamesession')),
            ],
        ),
    ]
