# Generated by Django 3.1.4 on 2020-12-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playboard',
            name='card_dict',
        ),
    ]
