# Generated by Django 3.1.4 on 2020-12-29 15:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_remove_playboard_card_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='playboard',
            name='card_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
