# Generated by Django 3.1.4 on 2020-12-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_playboard_card_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playboard',
            name='card_dict',
            field=models.JSONField(default=dict),
        ),
    ]
