# Generated by Django 3.1.4 on 2021-01-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0004_auto_20201229_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playboard',
            name='card_dict',
            field=models.JSONField(default=list),
        ),
    ]
