# Generated by Django 3.1.4 on 2021-01-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0005_auto_20210106_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='hasPicked',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hasPlayed',
        ),
        migrations.AddField(
            model_name='player',
            name='has_picked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='has_played',
            field=models.IntegerField(default=0),
        ),
    ]
