# Generated by Django 3.1.4 on 2021-01-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0006_auto_20210124_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='has_picked',
        ),
        migrations.RemoveField(
            model_name='player',
            name='has_played',
        ),
        migrations.AddField(
            model_name='player',
            name='hasPicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='hasPlayed',
            field=models.BooleanField(default=False),
        ),
    ]
